### ISSUE TITLE
create_introns() stalls on GRCz11 GFF

### ISSUE THREAD

**Issue by mmattocks** [daler/gffutils#111]
Hello,
 I am using gff utils with the GFF associated with the most recent zebrafish genome build (ftp://ftp.ensembl.org/pub/release-94/gff3/danio_rerio/Danio_rerio.GRCz11.94.gff3.gz).
In general this works fine. However, updating the database created from this GFF with create_introns() does not seem to work- it simply stalls out, with process CPU going to ~nil and no memory use. Not sure what's going on here. My code:
```
import gffutils

gff_file = <PATH>
db_path = <PATH>

db = gffutils.create_db(gff_file, db_path, disable_infer_transcripts=True, disable_infer_genes=True, merge_strategy="merge", verbose=True)
db.update(db.create_introns())
```
This is not a huge problem for me, the intron features would be convenient but aren't critical. I figured it would be good to report anyway.

**Comment by daler** [comment]
Thanks for reporting, and sorry I haven't gotten to this until now. 

For future reference: 

1. In that GTF, all CDSs for a protein have the same name. `merge_strategy="unique"` is a better choice
2. When updating the db, you should use the same kwargs as originally used when creating, otherwise it will spend a lot of time inferring genes and transcripts and dealing with the collisions between features.

```python
import gffutils
db = gffutils.create_db(
    'z11.gtf.gz', 'z11.db',
    disable_infer_transcripts=True,
    disable_infer_genes=True,
    verbose=True,
    merge_strategy="create_unique"
)

# sometimes you can get database locks if you're reading and writing
# at the same time -- this pulls out introns into a list
introns = list(db.create_introns())

db.update(
    introns,
    disable_infer_transcripts=True,
    disable_infer_genes=True,
    verbose=True,
    merge_strategy="create_unique"
)

```
