### ISSUE TITLE
change IDs in a GFF3 

### ISSUE THREAD

**Issue by mictadlo** [daler/gffutils#154]
Hi,
Are there any examples of how to change IDs in a GFF3 file and writing it back to a file?

Thank you in advance,

Michal

**Comment by daler** [comment]
If you're doing straightforward manipulation, you can bypass creating a database and just iterate of the features. Otherwise, if you need to modify IDs based on parents or children, you would need to create a database to build those hierarchical relationships and be able to access them.

Conceptually, you iterate through features, modify their attributes, and convert to string (printing it or writing to file as appropriate).

Here's an example of appending `_gene` to the end of each ID but only if the feature is of type `gene`:

```python
import gffutils
filename = gffutils.example_filename('FBgn0031208.gff')
with open('output.gff', 'w') as fout:
    for feature in gffutils.DataIterator(filename):
        if feature.featuretype == 'gene':
            feature.attributes["ID"] = feature.attributes["ID"] + "_gene"
        fout.write(str(feature) + '\n')
````
