### ISSUE TITLE
Database creation may be unnecessarily slow due to missing indexes

### ISSUE THREAD

**Issue by schelhorn** [daler/gffutils#48]
gffutils database creation may be unnecessarily slow since some sqlite indexes that are important for duplicate merging seem to be missing. The problematic part where the code spends most of the time is in [` _candidate_merges()`](https://github.com/daler/gffutils/blob/master/gffutils/create.py#L336). The joins in this function are expensive since apparently the `newid` and `idspecid` indexes are missing. I added

```python
        c.execute('CREATE UNIQUE INDEX featuresid ON features (id);')
        c.execute('CREATE UNIQUE INDEX dupnewid ON duplicates (newid);')
        c.execute('CREATE INDEX dupspecid ON duplicates (idspecid);')
        self.conn.commit()
```

[below the other index preparation steps](https://github.com/daler/gffutils/blob/master/gffutils/create.py#L881) which resulted in an about 100-fold faster database creation using these indexes.

As a side node, I also changed the default pragmas to further increase performance - but I believe the main boost came from the indexes alone:

```python
        pragmas = {'synchronous':'OFF', 'journal_mode': 'MEMORY', 'main.page_size': 4096,\
                   'main.cache_size': 100000, 'temp_store': 2, 'locking_mode': 'EXCLUSIVE'}
```

**Comment by daler** [comment]
Awesome!

Py3 compatibility was taking priority, but now that's finished I've been wanting to revisit performance. This is a clear performance bottleneck, thanks for identifying and fixing it.

There was a lot of related discussion over on #20, maybe this will fix some of the issues there.

It's up to you whether you want to submit a pull request (which travis-ci will test for you) or I can make these changes independently.

**Comment by schelhorn** [comment]
Great; please go ahead and make the changes yourself. I would appreciate it if you could then (after testing, of course) push a release to pypi relatively quickly since people downstream will not be aware of the changes otherwise. Thanks again for the fast fix.

**Comment by schelhorn** [comment]
Great; please go ahead and make the changes yourself. I would appreciate it if you could then (after testing, of course) push a release to pypi relatively quickly since people downstream will not be aware of the changes otherwise. Thanks again for the fast fix.

**Comment by daler** [comment]
@schelhorn, any chance there are entries for genes and transcripts in the GTF file you used for benchmarking? Do you get a similar speedup if, instead of making those indexes, you use `create_db(..., infer_gene_extent=False)` or `--disable-infer` from the CLI?

The reason I ask is because the format of some GTF files (Gencode I'm looking at you) is not on-spec GTF, so gffutils ends up doing a lot of unnecessary work.  I can't figure out how to get a permalink to a single comment on an issue, so I'll paste something I wrote over in #20:

>...Looking more closely, the Gencode v19 GTF file already has genes and transcripts inferred. So gffutils was spending a lot of effort to infer the extents of genes and transcripts. Then it would re-import them . . . only to find that they already existed in the database, which meant more effort figuring out how to merge them!

>So the second reason it's faster now is that I added a `infer_gene_extent` kwarg to `gffutils.create_db()`, and a corresponding `--disable-infer` argument to the gffutils-cli commandline tool.

>With these new changes (as of 4cb0cb8), it takes about 12 min to create a database out of the 2.6 million line Gencode v19 GTF file.

**Comment by schelhorn** [comment]
No, the `hg19` GTF I was working on only has only `transcript` features and no `gene` features, so I did not use the `infer_gene_extent` flag.

**Comment by daler** [comment]
Ah, I see.

The *default* is `infer_gene_extent=True`, which actually infers *both* gene and transcript.  So when you created your database it was trying to infer transcripts based on the exons, but getting tons of name collisions when it tried to add the inferred transcript back into the database since it was already there. It was doing a lot of extra work. The indexes you created help make that extra work faster, but it would be nice to avoid that extra work in the first place. 

(By the way, it was also inferring genes from transcripts, but that wasn't doing *extra* work.)

Up until now, I haven't seen a GTF file with transcripts but not genes. I think for your file, if you want to infer genes but not transcripts, you just need a `disable_infer_transcripts` option.

My design goal for gffutils is for it to handle as many GTF/GFF format variants as possible (see https://pythonhosted.org/gffutils/examples.html for some pathological cases).  In practice, this means adding more options during creation, rather than hard-coding optimizations into the schema that may actually slow down usage with other GFF/GTF format variants.

I agree that the indexes you add make sense and are definitely useful for this case. Before I add them though I want to do more benchmarking on a range of different files. But I will also work on a `disable_infer_transcript` option that -- if I'm understanding your file correctly -- should speed up creation even more than those indexes did.

Does this sound reasonable?

Also, is your GTF file from a public source so I could add it to the benchmarking and testing? If not, could you provide a representative snippet of it?

Thanks again.

**Comment by schelhorn** [comment]
That sounds very reasonable, thank you. The GTF in question is the standard RNA Seq annotation used by bcbio for hg19, as installed by [outbuildings]

**Comment by schelhorn** [comment]
That sounds very reasonable. Thank you. The GTF is the standard RNA annotation for hg19 used by bcbio as installed by cloudbiolinux.

**Comment by roryk** [comment]
I remove the gene features from that file as part of the cleaning step of that GTF file. That is a bad plan, I'll fix it so I stop doing that.

**Comment by daler** [comment]
There you go, simultaneous (within an hour of each other) fixes in two separate code bases for the same problem!

Specifically:

The previous behavior triggered by `infer_gene_extent=False` will be replaced with `disable_infer_transcripts=True` and `disable_infer_genes=True`. If you use the old `infer_gene_extent=False`, then these new settings will be automatically determined and you'll get a warning telling you about it.

In addition, to prevent this sort of thing in the future, there's a check inspired by what Rory has in `prepare_tx_gff.guess_infer_extent()`. This gives a warning if the GTF file already has transcript features but the default `disable_infer_transcripts=False` is set.

I made this backwards compatible, so hopefully everything on the bcbio side works fine, but you may get some warnings popping up now.

**Comment by roryk** [comment]
Thanks! That sounds perfect.

**Comment by schelhorn** [comment]
Great work, @daler, thanks!

**Comment by daler** [comment]
No prob, thanks for the input. BTW, v0.8.4rc1 is up on PyPI now.

I'll close this issue for now, but please reopen if the changes didn't work for some reason.
