### ISSUE TITLE
Merging GTF database and output results to a GTF file

### ISSUE THREAD

**Issue by guillermomarco** [daler/gffutils#57]
Hello @daler ,

I've been trying two merge features from two different GTF files/databases into a single "combined" GTF. I'm trying to merge an Ensembl GTF file with my features of interest from another GTF file (Cufflinks/Cuffcompare output)
So I've some questions I couldn't find answer reading the docs:

Fist one, since I want to output a single GTF as result of my merging features script: Is there any GTF writing method in gffutils? I know I can print features into an open file handler, but how do we deal with GTF/GFF headers?

Second, since I want to pick somefeatures from each GTF input dabase, my logical way to do this would be to create an empty db ("ouput_db" , I don't know if this is possible) and add interest features to this "ouput_db" and sort features by chromosome/start position and finally write them into output GTF file.

At this moment I'm at the point of picking my feature interest from both input gtf dbs, but I don't know how to merge them into a single db for sorting features and then write them to output.

Thanks!

**Comment by daler** [comment]
Hmm, in general, doesn't `cuffmerge` do what you're describing?

More specifically, writing to open filehandle currently is the best way to write output. I don't have anything built in that will dump the directives too. They're stored in the `directives` table of the db though and accessible through the `FeatureDB.directives` attribute, so you can just print them to file first.

If your end goal is a GTF file composed of features selected from input databases, then it might be easier and faster to write selected features from each input db to a single GTF file and then use sort or bedtools/pybedtools to operate on the file rather than pay the overhead of database creation.

**Comment by guillermomarco** [comment]
Yes `cuffmerge` can merge the original annotation GTF with the `cuffcompare` output.
I think I'll make a filtering/parsing script using `gffutils` that fits my needs then output filtered GTF to file. Then I'll try to merge both with `cuffmerge`

For sorting GTF with `bedtools` I'll have to test it, since this has got me serious headaches in the past.
Thanks @daler !

**Comment by daler** [comment]
`bedtools sort -i in.gff > out.gff` should do the trick for sorting. Also have a look at `pybedtools`, specifically the docs on [accessing GFF attributes](https://daler.github.io/pybedtools/intervals.html#gff-features-have-access-to-attributes). That can be useful if you don't need to navigate the hierarchy of gene/transcript/exon, in which case `gffutils` may be overkill.
