### ISSUE TITLE
Stuck on error: AttributeError: 'list' object has no attribute 'dialect'

### ISSUE THREAD

**Issue by rmzelle** [daler/gffutils#58]
Hi again,

I'm trying to update GFF features based on the attributes of their sibling or child, so I was trying to use `FeatureDB.iter_by_parent_childs()`. However, when I feed back the feature list to `FeatureDB.update()`, I keep getting the `AttributeError: 'list' object has no attribute 'dialect'` error, and I don't understand why. Could you have a quick look? I put a minimal example at https://gist.github.com/rmzelle/2dfd897a285c581c164b

[gffutils 0.8.7.1]

**Comment by daler** [comment]
Thanks for the minimal example, very helpful.

The issue here is that `db.update` needs an iterable of features, but the generator is creating an iterable of lists-of-features. Easiest way around that is to go one loop deeper in the generator, making sure it yields features and not lists of features. Changing the generator to the following did the trick:

```python
import gffutils
import os

genomeGFF = 'test.gff'
genomeGFFdb = 'test.db'

db = gffutils.create_db(genomeGFF, dbfn=genomeGFFdb, force=True, merge_strategy="merge")

def generatorModifyFeatures(featureFamilies):
    for featureFamily in featureFamilies:
        for i in featureFamily:
            print(i)
            yield i

featureFamilies = list(db.iter_by_parent_childs())
db.update(generatorModifyFeatures(featureFamilies), merge_strategy="replace")
```

**Comment by rmzelle** [comment]
Isn't 

```
[<Feature gene (scaffold10_size537661:22073-23956[-]) at 0x2c87f60L>, <Feature CDS (scaffold10_size537661:22076-23956[-]) at 0x2d7a6d8L>, <Feature exon (scaffold10_size537661:22076-23956[-]) at 0x2d7a9e8L>, <Feature mRNA (scaffold10_size537661:22073-23956[-]) at 0x2c93160L>]
```

(copied from my example output) already a list of features?

**Comment by rmzelle** [comment]
Anyway, it looks like I was confused by the description at http://daler.github.io/gffutils/autodocs/gffutils.interface.FeatureDB.update.html#gffutils.interface.FeatureDB.update:

> FeatureDB.update(data, make_backup=True, **kwargs)[source]
Update database with features in data.

> data : str, iterable, FeatureDB instance
If FeatureDB, all data will be used. If string, assume it’s a filename of a GFF or GTF file. **Otherwise, assume it’s an iterable of Feature objects.** The classes in gffutils.iterators may be helpful in this case.

I was under the assumption that list are a form of iterable (see e.g. http://stackoverflow.com/a/13054109/1712389), but I should just feed FeatureDB.update one feature at a time?

**Comment by daler** [comment]
Right, lists and generators are iterables. But this:
```
x = [1, 2, 3]
```
is different from 
```
y = [
   [1],
   [2],
   [3],
]
```

`x` is a list of integers, `y` is a list of lists. Sure, the nested lists in `y` are themselves iterables of integers, but `y` itself is a list of lists. Or an iterable of iterables, you could say. More specifically, an iterable of iterables of integers.

As you point out, in your example `featureFamily` is a list. That's what's being yielded each time through the loop in the generator function. So in the original example, `generatorModifyFeatures`  is an generator of lists -- an iterable of iterables like `y` above. The fix was to convert it into an iterable of `Feature`s, sort of like converting `y` to `x`.

**Comment by daler** [comment]
Another way of thinking about it is that `update` does this:
```
for i in x:
   # do something with i
```
and it expects `i` to be a `Feature`.  In this case, the [docs](https://docs.python.org/3/glossary.html#term-iterable) you linked to suggests that `x` should be considered an iterable.

In the case of a list, using `for` actually converts the list (an iterable) into an iterator (something that has `__next__` method). But `x` could already be an iterator that has a `__next__` method . . . like the generator in your example.

**Comment by rmzelle** [comment]
Okay, thanks for the explanation!
