### ISSUE TITLE
gffutils gets confused when using db.update() on subset of features?

### ISSUE THREAD

**Issue by rmzelle** [daler/gffutils#61]
Example at https://gist.github.com/rmzelle/256cbef7d594b518ac46

I'm trying to only update the features in my gffutils database that needed updating, but when I do that I get unexpected results. In particular, some features get deleted while others are duplicated, so it looks like gffutils sometimes misidentifies the features I'm trying to update. Any thoughts? How does gffutils establish which feature is which when using `db.update()`?

**Comment by rmzelle** [comment]
Bump. (would appreciate it a lot if you could take a quick look)

I wouldn't expect `db.update(generatorModifyFeatures(featureFamilies), merge_strategy="replace")` to have any effect on the contents of `db`.

**Comment by daler** [comment]
Sorry, I spent a while on this before and didn't see anything obvious; had to put it aside. Will take closer look this weekend. Thanks for the reminder.

**Comment by rmzelle** [comment]
It shouldn't be a problem that the generator doesn't always yield a feature in every iteration, right?

**Comment by daler** [comment]
Finally had a chance to look at this. It's subtle.

The issue is that there is a problem assigning unique IDs for features. By default, for GFF files `gffutils` uses the "ID" attribute to assign a unique ID in the database. But here, only `gene` features have an ID attribute. If there's no ID, then the fallback is to use the featuretype and an autoincrementing value. `Feature.id` stores this unique ID, so you can see what has been imported with, e.g., 

```python
[f.id for f in db.all_features()]
```

In general this autoincrementing works fine, but not when you want to merge/update with other features that don't have a unique ID. In particular, the non-ID-containing features are duplicated.

I also see that the parent/child relationship in this example won't be build correctly. The exons specify the gene ID as the parent rather than the transcript.

The solution to these issues is to transform the features as they are being imported into the database to 1) ensure they have unique IDs so that merging happens correctly and 2) change the "Parent" attribute of exons and CDSs such that they point to the transcript rather than the gene.

In the `transform()` function, for featuretypes that don't have ID attributes in your example file, I'm creating one. For mRNA, it's the transcript_id field. For exon/CDS, I'm making one based on attributes and fields that appear to uniquely identify them across the file. You may need more or less info to uniquely identify an exon in a real-world case. Then in both `create_db` and `db.update`, I'm specifying both the new transform function and explicitly using "ID" as the id_spec.

Doing so makes `test-unchanged.gff` and `test-updated.gff` identical.

```python
# . . . stuff from https://gist.github.com/rmzelle/256cbef7d594b518ac46 . . . then,

def transform(f):
    """
    ensure all features have an ID attribute; fix exon/CDS
    parents to point to transcript
    """
    if f.featuretype == 'gene':
        pass
    if f.featuretype == 'mRNA':
        f['ID'] = f['transcript_id']
    if f.featuretype in ['exon', 'CDS']:
        f['Parent'] = f['transcript_id']
        f['ID'] = ['%s_%s:%s-%s_%s' % 
            (f.featuretype, f.chrom, f.start, f.stop, f['Parent'][0])]
    return f

db = gffutils.create_db(genomeGFF, dbfn=genomeGFFdb, force=True,
                        keep_order=True, merge_strategy="warning",
                        id_spec='ID', transform=transform)

# . . . other stuff from
#  https://gist.github.com/rmzelle/256cbef7d594b518ac46
# . . . then,

db.update(generatorModifyFeatures(featureFamilies), merge_strategy="replace",
          id_spec="ID", transform=transform)


```

**Comment by rmzelle** [comment]
Thanks for digging into this! I'll give it a try.
