### ISSUE TITLE
UNIQUE constraint failed: features.id

### ISSUE THREAD

**Issue by teshomem** [daler/gffutils#68]
I am not able to load the database in memory. However, I was able to save it in disk.

>>> fn = gffutils.example_filename('/local/genome/references/Salmo_salar/ICSASG_v2/annotation_RefSeq_100/GCF_000233375.1_ICSASG_v2_genomic.gff')
>>> db = gffutils.create_db(fn, ':memory:')
Traceback (most recent call last):
  File "/local/genome/packages/anaconda3/2.4.1/lib/python3.5/site-packages/gffutils/create.py", line 569, in _populate_from_lines
    self._insert(f, c)
  File "/local/genome/packages/anaconda3/2.4.1/lib/python3.5/site-packages/gffutils/create.py", line 510, in _insert
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.IntegrityError: UNIQUE constraint failed: features.id

GFF file is ftp://ftp.ncbi.nlm.nih.gov/genomes/Salmo_salar/GFF/ref_ICSASG_v2_top_level.gff3.gz

Thanks.

**Comment by daler** [comment]
Neither memory nor disk will work with default parameters on this GFF file. That's because this file has multiple CDSs with the same ID, which results in a name collision when importing into the database.

See the [docs for `create_db`](http://daler.github.io/gffutils/autodocs/gffutils.create.create_db.html#gffutils.create.create_db) to decide on a merge strategy to use, depending on how you want to handle those CDSs. Perhaps you want `merge_strategy="create_unique"`?

**Comment by teshomem** [comment]
Thanks. I just realized that used the merge strategy when I saved it to disk.

**Comment by daler** [comment]
Ok, good.
