### ISSUE TITLE
Is there a bidirectional promoter feature?

### ISSUE THREAD

**Issue by adomingues** [daler/gffutils#78]
Hi Ryan,

I  am looking into thee possibility of using gffutils to select genes from an encode gff that have bidirectional promoters. I noticed that the old (old) version of gffutils had this [functionality](https://github.com/daler/GFFutils_old/blob/8e032cdcfe83dbc1ec85e55cbf6bcc72a0059328/README.rst#id24), but it appears to have been dropped. Is this correct? If yes, how would one go about filtering (out) genes that have neighbouring TSSs? 

Cheers

**Comment by daler** [comment]
Yep, this has been dropped. For this kind of analysis I would use [`pybedtools`](https://daler.github.io/pybedtools/index.html) instead. 

See the [`gffutils.pybedtools_integration.tsses`](http://daler.github.io/gffutils/autodocs/gffutils.pybedtools_integration.tsses.html#gffutils.pybedtools_integration.tsses) for getting TSSs from a FeatureDB and converting to a BedTool; from there you'll probably want to use `BedTool.closest(D="a", io=True)` and filter on the distance reported in the last column.

Here's something to get you started:

```python
import gffutils
import pybedtools
from gffutils.pybedtools_integration import tsses

# small example file
fn = gffutils.example_filename('gencode-v19.gtf')
db = gffutils.create_db(
    fn,
    ":memory:",
    keep_order=True,
    disable_infer_genes=True,
    disable_infer_transcripts=True)

# see docs for details; you'll probably want to customize
x = tsses(db)

# negative distances mean upstream; ignore overlapping. 
y = x.closest(x, D="a", io=True)

# depending on what you want to do with it, either convert to dataframe
# for downstream stuff...
df = y.to_dataframe()

# ...or keep only tsses whose closest TSS is farther than
# some distance upstream
def far_enough_upstream(f, dist):
    d = int(f[-1])
    return (d < 0) and (d < -dist)

z = y.filter(far_enough_upstream, 100).cut(range(9)).saveas()

```
From there, you could work with the dataframe (prob more convenient, but would need a lot of memory) or add more logic to the filter function (additional complexity, but only one feature in memory at a time) to identify TSSs with different gene parents that are on opposing strands and where the lower-coordinate TSS is minus-strand (to catch divergent rather than convergent).
