### ISSUE TITLE
Case-insensitive retrieval of key-value pairs from the attributes field

### ISSUE THREAD

**Issue by arnikz** [daler/gffutils#81]
Hi,

I have a couple of GFF files which differ in the use of case for key-value pairs in the attributes field.
For example, one file contains _Name=..._ and the other _name=..._. To fetch the values of both keys two _feature.attributes.get()_ calls are needed. With more keys (of this kind) the app code becomes cluttered. The attributes fields in the database(s) could be stored as is in the original GFF file(s). Would it be an idea to implement this feature e.g. in the form of _gffutils.constants.case_sensitive_get=False_? Thank you.

**Comment by daler** [comment]
I'd rather not add something like this to gffutils since while it would simplify your code, it would do so at the cost of extra complexity for *all* users of gffutils. It's the first time I've heard of this issue so I suspect it's not widespread. Where is the problematic GFF file coming from (the one with *name=...*)? While nobody seems to follow the GFF spec, in my experience there has at least been a consensus to use uppercase attribute names. Can you get it fixed upstream?

Otherwise, you could simplify your code with a function like:

```python
def getfeatureattr(f, attr):
    try:
        return f[attr]
    except KeyError:
        return f[attr.lower()]
```

**Comment by arnikz** [comment]
Good point. You can find an example [here](http://solanaceae.plantbiology.msu.edu/data/PGSC_DM_V403_genes.gff.zip).
