### ISSUE TITLE
Attribute values lack percent-decoding

### ISSUE THREAD

**Issue by timdiels** [daler/gffutils#98]
Could percent-encoded characters be decoded by default? See https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md#description-of-the-format

```python
>>> gffutils.feature.feature_from_line('chr1\tAUGUSTUS\tgene\t6950084\t6951407\t0.26\t-\t.\tID=INIL01g00009;GeneSymbol=Ndufaf6;Note=NADH dehydrogenase (ubiquinone) complex I%2C assembly factor 6;GO_Terms=GO:0005743|GO:0016740|GO:0009058|GO:0032981;PFam=PF00494')['Note']
['NADH dehydrogenase (ubiquinone) complex I%2C assembly factor 6']
```

`urllib.parse.unquote` should do the trick:

```python
>>> [urllib.parse.unquote(value) for value in feature['Note']]
['NADH dehydrogenase (ubiquinone) complex I, assembly factor 6']
```

Thanks for the great library

**Comment by daler** [comment]
I see how it would be useful, but it is unclear to me at what point the decoding should happen. For example, if decoding happens when parsing the original file, we lose round-trip invariance since what's stored in the db does not match what's in the file. Storing two versions in the db, original and decoded, will add time and complexity and space and I'd rather not go there.

What about decoding when reading from the db? Should the decoding happen when populating the attributes, such that the user never sees the `%2C`? Or decode only when calling `__str__` on the Feature object? Actually, that would break round-trip invariance as well. Or should we do as you show here, decode all individual values for each attribute when accessing the values, but not when calling `__str__`?

Since there's not a clear place to decode that would make sense for all use-cases, I think I would prefer at the moment to be explicit and have it be up to the user to do this when it's needed.

**Comment by timdiels** [comment]
So by round-trip invariance you mean that parsing a GFF file and printing out its features should yield the original GFF file. I.e `encode(decode(value)) == value` + parsing/writing the file.

If `encode = urllib.parse.unquote` and `decode = lambda x: x.replace(',', '%2c')` (and more `replace`/regex or something equivalent for all the other characters that must be encoded), the above property holds, unless I'm missing something. Since `%` must be encoded, `unquote` will not decode too much. Further, since each character either must be encoded or musn't be encoded (according to GFF spec, i.e. there is no choice in the matter), and there is only one way to encode each character, there is no ambiguity in re-encoding characters.

I would find it most intuitive if the values are stored decoded in the database and are only re-encoded in the return of `str(feature)` as the latter tries to show the line as it appeared in the file.

**Comment by daler** [comment]
I agree. But a huge problem with GTF/GFF files in the wild is that they don't follow the spec, and one of my goals with gffutils is to still support those crazy derivatives. I could have sworn I had played with this in the past, and after a quick check looks like I did [here](https://github.com/daler/gffutils/blob/master/gffutils/parser.py#L275):

```python
        # TODO: urllib.unquote breaks round trip invariance for "hybrid1.gff3"
        # test file.  This is because the "Note" field has %xx escape chars,
        # but "Dbxref" has ":" which, if everything were consistent, should
        # have also been escaped.
        #
        # (By the way, GFF3 spec says only literal use of \t, \n, \r, %, and
        # control characters should be encoded)
        #
        # Solution 1: don't unquote
        # Solution 2: store, along with each attribute, whether or not it
        #             should be quoted later upon reconstruction
        # Solution 3: don't care about invariance
       # unquoted = [urllib.unquote(v) for v in vals]
```

So it looks like I went with the don't-unquote strategy. However I don't think it's appropriate to avoid useful functionality solely based on corner cases. How about adding a config option `constants.ignore_url_escape_characters` which is by default False to support unquoting before storing in the database, but can be set to True in cases like the above problematic example?

In such corner cases, it would be important to set it to True when writing out in order to get round trip invariance. Maybe the value of `ignore_url_escape_characters` could be stored in the database's `meta` table for persistence. Then in a later session, if that `meta` value is not consistent with the current `ignore_url_escape_characters`, a warning/reminder can be printed when a connection to the db is made.

**Comment by timdiels** [comment]
Ah yes, I know that pain all too well; I usually use some `perl -pe`s to fix them. I like the `ignore_url_escape_characters` idea, sounds good.

**Comment by daler** [comment]
@timdiels can you try the recent changes to see how they work for you? (specifically in #100)

**Comment by timdiels** [comment]
Issue persists with [the gff file I'm using (9.5MB)](https://floppy.psb.ugent.be/public.php?service=files&t=9a66b596e4967b818818e5eab80c3237). E.g.

```python
>>> gff['INIL01g00043']['Note']
['2%2C3-bisphosphoglycerate-dependent phosphoglycerate mutase {ECO:0000255|HAMAP-Rule:MF_01039}']
```

`feature_from_line` does work on that line:

```python
>>> line = 'chr1\tAUGUSTUS\tgene\t7929411\t7933164\t0.09\t+\t.\tID=INIL01g00043;GeneSymbol=gpmA;Note=2%2C3-bisphosphoglycerate-dependent phosphoglycerate mutase {ECO:0000255|HAMAP-Rule:MF_01039};GO_Terms=GO:0046538|GO:0006094|GO:0006096;PFam=PF00300'
>>> f=gffutils.feature.feature_from_line(line)
>>> f['Note']
['2,3-bisphosphoglycerate-dependent phosphoglycerate mutase {ECO:0000255|HAMAP-Rule:MF_01039}']
```

and `create_db` on a gff file containing just that line also works. But when using the full file, the `%` is still there:

```python
>>> gff=gffutils.create_db('tmp.gff', 'tmp.db', id_spec='ID', verbose=True, merge_strategy='create_unique')
2017-08-08 15:27:13,056 - INFO - Populating features
2017-08-08 15:29:15,069 - INFO - Populating features table and first-order relations: 894041 features
2017-08-08 15:29:15,070 - INFO - Updating relations
2017-08-08 15:29:40,542 - INFO - Creating relations(parent) index
2017-08-08 15:29:57,847 - INFO - Creating relations(child) index
2017-08-08 15:30:11,261 - INFO - Creating features(featuretype) index
2017-08-08 15:30:15,328 - INFO - Creating features (seqid, start, end) index
2017-08-08 15:30:19,202 - INFO - Creating features (seqid, start, end, strand) index
2017-08-08 15:30:23,856 - INFO - Running ANALYSE features
>>> gff['INIL01g00043']['Note']
['2%2C3-bisphosphoglycerate-dependent phosphoglycerate mutase {ECO:0000255|HAMAP-Rule:MF_01039}']
```

(To make sure I used the correct version, I checked out `0af2a58734a0d` and printed something in `gffutils/__init__.py`)

**Comment by daler** [comment]
Thanks, I think I fixed it now. Tests passed and I merged into master, can you check the master branch now please?

**Comment by timdiels** [comment]
Indeed it works, thanks
